### ISSUE TITLE
`DUMP_FAILURES_EDIT_COMMAND` exists in `dump_failures`, add documentation

### ISSUE THREAD

**Issue by jmaher** [mozilla/mozci-tools#10]
there is code in `dump_failures` to look for an environment variable and take action:
```
            if "DUMP_FAILURES_EDIT_COMMAND" in os.environ:
                context.insert(0, test)
                context = [line.strip() for line in context]
                context = '","'.join(context)
                context = f'["{context}"]'
                cmd = shlex.split(
                    os.environ["DUMP_FAILURES_EDIT_COMMAND"].format(
                        test=os.path.basename(test), manifest=manifest, context=context
                    )
                )
                subprocess.run(cmd)
```

This is not documented without reading the source code, and it should be.  

How do you know what DUMP_FAILURES_EDIT_COMMAND does... ?  I would look at the comment at the top of the file for a pointer, then try it out so you can see how it works.

I would like see this added to the usage documentation:
https://github.com/mozilla/mozci-tools/tree/main/docs

To add to the docs would be an example of an environment variable to set and output to expect, along with any other requirements needed.

Of course the ultimate goal is to have commands that edit manifests seamlessly, so documenting this shows a sort of hybrid tooling/manual process

**Comment by ahal** [comment]
Yeah, this was a bit of a hack I wrote to make the failure results automatically show up in my `vim`. I'm not really sure how this "feature" can integrate nicely into the script or not, but it should likely be refactored or removed or something.
