### ISSUE TITLE
Create a `config` subcommand to help edit the `mozci` configuration file

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci-tools#13]
There is a [configuration file](https://github.com/mozilla/mozci/blob/master/mozci/configuration.py#L98) in mozci that contains variables that can control certain aspects of how mozci runs. 

It would be nice if we could a command like `$ citools config` that could open this file in your editor. This will involve adding a new subcommand to cleo here:
https://github.com/mozilla/mozci-tools/blob/main/citools/console/application.py#L10

Documentation for cleo can be found here:
https://cleo.readthedocs.io/en/latest/

**Comment by Remi288** [comment]
I will like to work on this, as an outreachy appilcant.

**Comment by ahal** [comment]
Thanks for your interest! I've assigned you, let me know if you have any questions.

**Comment by Remi288** [comment]
Hi @ahal , I have been able to implement the subcommand using a file in the same repo, I will like to know if the configuration file in mozci will be pass as an argument or it will  be fetch from mozci repo.

**Comment by Remi288** [comment]
Alright, thanks!

**Comment by jmaher** [comment]
@ahal can we close this issue or is there more to do here?

**Comment by ahal** [comment]
Yes thanks for noticing!
